[build]
  publish = "frontend/dist"
  command = "cd frontend && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://newrevolution-backend.onrender.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://newrevolution-backend.onrender.com"