services:
  - type: web
    name: newrevolution-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirments.txt
    startCommand: gunicorn newrevolution.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    healthCheckPath: /health/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: postgresql://postgres.sbykzpirrgeceecxvpvc:your-password@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      - key: RESEND_API_KEY
        value: re_Gca9oy8H_CCEZJoVtjEAtqh3WK68YDnRY
      - key: DEFAULT_FROM_EMAIL
        value: noreply@newrevolution.com
      - key: FRONTEND_DOMAIN
        value: https://newrevolution.netlify.app
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1,.onrender.com,newrevolution-backend.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        value: your-cloud-name
      - key: CLOUDINARY_API_KEY
        value: your-api-key
      - key: CLOUDINARY_API_SECRET
        value: your-api-secret
      - key: STRIPE_SECRET_KEY
        value: sk_test_your-stripe-key
      - key: ADMIN_URL
        value: admin/
